### PR TITLE
URI encode only if ids are json strings

### PR DESCRIPTION
**Pull request by michaelmattig**

### CODE REVIEW

**Comment by michaelmattig** [comment]
[[GEO BON] 1.x LayerAPI umsetzen](https://trello.com/c/W4pWeL0N/919-geo-bon-1x-layerapi-umsetzen)

**Review by ChristianBeilschmidt — CHANGES_REQUESTED** [review]
https://github.com/geo-engine/geoengine-ui/blob/9412a12d904adc11f6f74068e993ee2a1c988fa3/projects/dashboards/ebv-analyzer/src/app/ebv-selector/ebv-selector.component.ts#L48

**Comment by ChristianBeilschmidt** [comment]
grafik

Something isn't right. The autofill does not work anymore.

**Comment by michaelmattig** [comment]
> grafik
> 
> Something isn't right. The autofill does not work anymore.

f829f559d70f29ac3f6f17090a8d19693835b046

**Review by ChristianBeilschmidt — APPROVED** [review]

**Comment by ChristianBeilschmidt** [comment]
bors merge

**Pull request merged**
