### PR TITLE
bugfix:Layer Menu Button is back again

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
[Fehlender Button im Gfbio Dashboard](https://trello.com/c/ArBrVCKM/1234-fehlender-button-im-gfbio-dashboard)

**Comment by jdroenner** [comment]
bors merge

**Review by jdroenner — APPROVED** [review]

**Comment by jdroenner** [comment]
bors mege

**Comment by jdroenner** [comment]
bors merge

**Pull request merged**
