### PR TITLE
query API layers for ebv portal

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
[Die Portal-API von GEO BON anbinden](https://trello.com/c/j9nmED8g/580-die-portal-api-von-geo-bon-anbinden)

**Comment by michaelmattig** [comment]
maybe we should create an actual model for the ebv responses, like we do for all other api calls

**Comment by ChristianBeilschmidt** [comment]
> maybe we should create an actual model for the ebv responses, like we do for all other api calls

I thought these are `Array<EbvClass>>` and `Array<EbvDataset>`.

**Review by michaelmattig — APPROVED** [review]

**Comment by michaelmattig** [comment]
bors merge

**Pull request merged**
