### PR TITLE
EBV: new name for back button

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
[GeoBON zurück zu button anders beschriften](https://trello.com/c/QOT3Ko1U/878-geobon-zur%C3%BCck-zu-button-anders-beschriften)

**Review by jdroenner — APPROVED** [review]

**Comment by jdroenner** [comment]
bors merge

**Comment by jdroenner** [comment]
bors retry

**Comment by jdroenner** [comment]
bors retry

**Comment by jdroenner** [comment]
bors retry

**Comment by jdroenner** [comment]
bors retry

**Comment by jdroenner** [comment]
bors retry

**Pull request merged**
