### PR TITLE
fix for time step

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**

### CODE REVIEW

**Review by jdroenner — APPROVED** [review]

**Comment by jdroenner** [comment]
bors merge

**Review by jdroenner — APPROVED** [review]

**Comment by jdroenner** [comment]
bors merge

**Comment by ChristianBeilschmidt** [comment]
bors merge

**Review by jdroenner — APPROVED** [review]

**Comment by jdroenner** [comment]
bors merge

**Pull request merged**
