### PR TITLE
add interpolation operator

### PR DESCRIPTION
**Pull request by michaelmattig**

### CODE REVIEW

**Comment by michaelmattig** [comment]
[[RESPECT M.1] Dateninterpolation](https://trello.com/c/666qNh0F/973-respect-m1-dateninterpolation)

**Comment by ChristianBeilschmidt** [comment]
grafik

Please fix that the error is shown correctly.

**Comment by michaelmattig** [comment]
68d554f3260ba35999cab712dc8316bd2a930a40

**Review by ChristianBeilschmidt — APPROVED** [review]

**Comment by ChristianBeilschmidt** [comment]
bors merge

**Pull request merged**
