### PR TITLE
dataset-scrolling

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
[Dataset-Listing](https://trello.com/c/KFXACQ0R/298-dataset-listing)

**Comment by michaelmattig** [comment]
- why did you style the datasets differently? they now have different fonts/sizes than the other elements in the sidebar
- can you a void the initial debounce? If I open the datasets it takes longer than before until the datasets are shown
- I added a bunch of datasets, scrolled down and this happpened. it shouldn't request the same data multiple times
grafik

**Review by michaelmattig — CHANGES_REQUESTED** [review]
.

**Comment by ChristianBeilschmidt** [comment]
>     * why did you style the datasets differently? they now have different fonts/sizes than the other elements in the sidebar

5995f42  and 
68137fa 
> 
>     * can you avoid the initial debounce? If I open the datasets it takes longer than before until the datasets are shown
5995f42  and 
68137fa 

> 
>     * I added a bunch of datasets, refreshed the page, went to the datasets, scrolled down and this happpened. it shouldn't request the same data multiple times
>       grafik

2392e9b

**Pull request merged**
